DATASETS:
    NAME: "breast_cancer"
    CLASS: 2

MODEL:
    META_ARCHITECTURE: "UciNet"
    DH: 3
    DW: 3
    N_MUL: 50
    DD: 10
    N_PER_GROUP: 1

    FC:
        N_FC: 64
        B_FC: True

SOLVER:
    NUM_ROUNDS: 5
    MAX_EPOCHS: 50
    TRAIN_PER_BATCH: 512
    TEST_PER_BATCH: 512
    LR: 5e-4
    LR_SCHEDULER_ON: False
    WEIGHT_DECAY: 1e-4
    OPTIMIZER: Adam

OUTPUT_DIR:
    "Results/uci/breast_cancer"

