DATASETS:
    NAME: "mammographic_masses"
    CLASS: 2
    CREATE_MISSING: False
    K_FOLD_NUMBER: 10

MODEL:
    META_ARCHITECTURE: "UciNet"
    DH: 3
    DW: 3
    N_MUL: 100
    DD: 5
    N_PER_GROUP: 1

    FC:
        N_FC: 128
        B_FC: True

    #RESUME: "Results/uci/usps/frac_0.1/checkpoint.pth.tar"

SOLVER:
    NUM_ROUNDS: 1
    MAX_EPOCHS: 20
    TRAIN_PER_BATCH: 32
    TEST_PER_BATCH: 32
    LR: 1e-4
    LR_SCHEDULER_ON: False
    WEIGHT_DECAY: 1e-4
    OPTIMIZER: Adam

OUTPUT_DIR:
    "Results/uci/mammographic_masses"
