DATASETS:
    NAME: "svmguide3"
    CLASS: 2

MODEL:
    META_ARCHITECTURE: "UciNet"
    DH: 3
    DW: 3
    N_MUL: 10
    DD: 22
    N_PER_GROUP: 1

    FC:
        N_FC: 128
        B_FC: True

SOLVER:
    NUM_ROUNDS: 5
    MAX_EPOCHS: 100
    TRAIN_PER_BATCH: 32
    TEST_PER_BATCH: 32
    LR: 1e-4
    LR_SCHEDULER_ON: False
    WEIGHT_DECAY: 1e-4
    OPTIMIZER: Adam

OUTPUT_DIR:
    "Results/uci/svmguide3"

